const authors = [
	{
		email: "author1@gmail.com",
		phoneNumber: "89500335271",
		verifiedByEmail: true,
		role: "автор",
		firstName: "Дмитрий",
		lastName: "Федоров",
		middleName: "Петрович",
		dateOfBirth: "17.03.1998",

		authorStatus: "Молодой ученый",
		region: "Респ. Башкортостан",
		city: "Уфа",
		university: "Уфимский Университет Науки и Технологий",
		faculty: "ИИМРТ",
		department: "ВМК",
		course: 4,
		groupNumber: "ПРО-428",
	},
	{
		email: "author2@gmail.com",
		phoneNumber: "89500335272",
		verifiedByEmail: true,
		role: "автор",
		firstName: "Екатерина",
		lastName: "Семенова",
		middleName: "Андреевна",
		dateOfBirth: "25.05.1999",

		authorStatus: "Специалитет",
		region: "Респ. Башкортостан",
		city: "Уфа",
		university: "Уфимский Университет Науки и Технологий",
		faculty: "ИТМ",
		department: "Информатика",
		course: 5,
		groupNumber: "ИНФ-523",
	},
	{
		email: "author3@gmail.com",
		phoneNumber: "89500335273",
		verifiedByEmail: true,
		role: "автор",
		firstName: "Александр",
		lastName: "Григорьев",
		middleName: "Ильич",
		dateOfBirth: "10.08.2000",

		authorStatus: "Бакалавриат",
		region: "Респ. Башкортостан",
		city: "Уфа",
		university: "Уфимский Университет Науки и Технологий",
		faculty: "ФАДЭТ",
		department: "Математика",
		course: 4,
		groupNumber: "МАТ-418",
	},
	{
		email: "author4@gmail.com",
		phoneNumber: "89500335274",
		verifiedByEmail: true,
		role: "автор",
		firstName: "Виктория",
		lastName: "Киселева",
		middleName: "Николаевна",
		dateOfBirth: "12.12.2001",

		authorStatus: "Магистрант",
		region: "Респ. Башкортостан",
		city: "Уфа",
		university: "Уфимский Университет Науки и Технологий",
		faculty: "ПИШ",
		department: "Биология",
		course: 2,
		groupNumber: "БИО-224",
	},
	{
		email: "author5@gmail.com",
		phoneNumber: "89500335275",
		verifiedByEmail: true,
		role: "автор",
		firstName: "Никита",
		lastName: "Соколов",
		middleName: "Андреевич",
		dateOfBirth: "28.02.1997",

		authorStatus: "Аспирант",
		region: "Респ. Башкортостан",
		city: "Уфа",
		university: "Уфимский Университет Науки и Технологий",
		faculty: "ИИГУ",
		department: "Химия",
		course: 3,
		groupNumber: "ХИМ-328",
	},
	{
		email: "author6@gmail.com",
		phoneNumber: "89500335276",
		verifiedByEmail: true,
		role: "автор",
		firstName: "Ольга",
		lastName: "Морозова",
		middleName: "Викторовна",
		dateOfBirth: "04.01.2002",

		authorStatus: "Бакалавриат",
		region: "Респ. Башкортостан",
		city: "Уфа",
		university: "Уфимский Университет Науки и Технологий",
		faculty: "ИТМ",
		department: "Информатика",
		course: 3,
		groupNumber: "ИНФ-323",
	},
	{
		email: "author7@gmail.com",
		phoneNumber: "89500335277",
		verifiedByEmail: true,
		role: "автор",
		firstName: "Андрей",
		lastName: "Новиков",
		middleName: "Сергеевич",
		dateOfBirth: "14.06.1995",

		authorStatus: "Магистрант",
		region: "Респ. Башкортостан",
		city: "Уфа",
		university: "Уфимский Университет Науки и Технологий",
		faculty: "ФАДЭТ",
		department: "Математика",
		course: 1,
		groupNumber: "МАТ-118",
	},
	{
		email: "author8@gmail.com",
		phoneNumber: "89500335278",
		verifiedByEmail: true,
		role: "автор",
		firstName: "Светлана",
		lastName: "Сидорова",
		middleName: "Алексеевна",
		dateOfBirth: "02.07.1996",

		authorStatus: "Молодой ученый",
		region: "Респ. Башкортостан",
		city: "Уфа",
		university: "Уфимский Университет Науки и Технологий",
		faculty: "ИИГУ",
		department: "Физика",
		course: 4,
		groupNumber: "ФИЗ-428",
	},
	{
		email: "author9@gmail.com",
		phoneNumber: "89500335279",
		verifiedByEmail: true,
		role: "автор",
		firstName: "Ирина",
		lastName: "Павлова",
		middleName: "Михайловна",
		dateOfBirth: "25.09.1998",

		authorStatus: "Специалитет",
		region: "Респ. Башкортостан",
		city: "Уфа",
		university: "Уфимский Университет Науки и Технологий",
		faculty: "ИТМ",
		department: "Информатика",
		course: 5,
		groupNumber: "ИНФ-523",
	},
	{
		email: "author10@gmail.com",
		phoneNumber: "89500335280",
		verifiedByEmail: true,
		role: "автор",
		firstName: "Владимир",
		lastName: "Зайцев",
		middleName: "Иванович",
		dateOfBirth: "19.11.1997",

		authorStatus: "Бакалавриат",
		region: "Респ. Башкортостан",
		city: "Уфа",
		university: "Уфимский Университет Науки и Технологий",
		faculty: "ФАДЭТ",
		department: "Математика",
		course: 4,
		groupNumber: "МАТ-418",
	},
	// ... Continue to add more authors in similar fashion
	{
		email: "author11@gmail.com",
		phoneNumber: "89500335281",
		verifiedByEmail: true,
		role: "автор",
		firstName: "Григорий",
		lastName: "Иванов",
		middleName: "Алексеевич",
		dateOfBirth: "15.01.1996",

		authorStatus: "Аспирант",
		region: "Респ. Башкортостан",
		city: "Уфа",
		university: "Уфимский Университет Науки и Технологий",
		faculty: "ПИШ",
		department: "Биология",
		course: 3,
		groupNumber: "БИО-328",
	},
	{
		email: "author12@gmail.com",
		phoneNumber: "89500335282",
		verifiedByEmail: true,
		role: "автор",
		firstName: "Татьяна",
		lastName: "Кириллова",
		middleName: "Сергеевна",
		dateOfBirth: "22.04.1998",

		authorStatus: "Бакалавриат",
		region: "Респ. Башкортостан",
		city: "Уфа",
		university: "Уфимский Университет Науки и Технологий",
		faculty: "ИГСН",
		department: "История",
		course: 4,
		groupNumber: "ИСТ-428",
	},
	{
		email: "author13@gmail.com",
		phoneNumber: "89500335283",
		verifiedByEmail: true,
		role: "автор",
		firstName: "Сергей",
		lastName: "Медведев",
		middleName: "Олегович",
		dateOfBirth: "11.03.2001",

		authorStatus: "Магистрант",
		region: "Респ. Башкортостан",
		city: "Уфа",
		university: "Уфимский Университет Науки и Технологий",
		faculty: "ИИМРТ",
		department: "Физика",
		course: 2,
		groupNumber: "ФИЗ-224",
	},
	{
		email: "author14@gmail.com",
		phoneNumber: "89500335284",
		verifiedByEmail: true,
		role: "автор",
		firstName: "Полина",
		lastName: "Орлова",
		middleName: "Валерьевна",
		dateOfBirth: "30.06.1995",

		authorStatus: "Молодой ученый",
		region: "Респ. Башкортостан",
		city: "Уфа",
		university: "Уфимский Университет Науки и Технологий",
		faculty: "ИТМ",
		department: "Информатика",
		course: 4,
		groupNumber: "ИНФ-428",
	},
	{
		email: "author15@gmail.com",
		phoneNumber: "89500335285",
		verifiedByEmail: true,
		role: "автор",
		firstName: "Алексей",
		lastName: "Захаров",
		middleName: "Андреевич",
		dateOfBirth: "18.09.1994",

		authorStatus: "Специалитет",
		region: "Респ. Башкортостан",
		city: "Уфа",
		university: "Уфимский Университет Науки и Технологий",
		faculty: "ПИШ",
		department: "Биология",
		course: 5,
		groupNumber: "БИО-528",
	},
	{
		email: "author16@gmail.com",
		phoneNumber: "89500335286",
		verifiedByEmail: true,
		role: "автор",
		firstName: "Евгения",
		lastName: "Голубева",
		middleName: "Николаевна",
		dateOfBirth: "09.12.1997",

		authorStatus: "Аспирант",
		region: "Респ. Башкортостан",
		city: "Уфа",
		university: "Уфимский Университет Науки и Технологий",
		faculty: "ИИГУ",
		department: "Химия",
		course: 3,
		groupNumber: "ХИМ-328",
	},
	{
		email: "author17@gmail.com",
		phoneNumber: "89500335287",
		verifiedByEmail: true,
		role: "автор",
		firstName: "Наталья",
		lastName: "Коваленко",
		middleName: "Александровна",
		dateOfBirth: "01.01.2000",

		authorStatus: "Бакалавриат",
		region: "Респ. Башкортостан",
		city: "Уфа",
		university: "Уфимский Университет Науки и Технологий",
		faculty: "ИГСН",
		department: "История",
		course: 4,
		groupNumber: "ИСТ-428",
	},
	{
		email: "author18@gmail.com",
		phoneNumber: "89500335288",
		verifiedByEmail: true,
		role: "автор",
		firstName: "Михаил",
		lastName: "Крылов",
		middleName: "Владимирович",
		dateOfBirth: "13.07.1998",

		authorStatus: "Магистрант",
		region: "Респ. Башкортостан",
		city: "Уфа",
		university: "Уфимский Университет Науки и Технологий",
		faculty: "ИИМРТ",
		department: "Физика",
		course: 2,
		groupNumber: "ФИЗ-224",
	},
	{
		email: "author19@gmail.com",
		phoneNumber: "89500335289",
		verifiedByEmail: true,
		role: "автор",
		firstName: "Елена",
		lastName: "Зайцева",
		middleName: "Игоревна",
		dateOfBirth: "07.05.2001",

		authorStatus: "Молодой ученый",
		region: "Респ. Башкортостан",
		city: "Уфа",
		university: "Уфимский Университет Науки и Технологий",
		faculty: "ИТМ",
		department: "Информатика",
		course: 3,
		groupNumber: "ИНФ-323",
	},
	{
		email: "author20@gmail.com",
		phoneNumber: "89500335290",
		verifiedByEmail: true,
		role: "автор",
		firstName: "Даниил",
		lastName: "Борисов",
		middleName: "Викторович",
		dateOfBirth: "25.12.1996",

		authorStatus: "Специалитет",
		region: "Респ. Башкортостан",
		city: "Уфа",
		university: "Уфимский Университет Науки и Технологий",
		faculty: "ФАДЭТ",
		department: "Математика",
		course: 5,
		groupNumber: "МАТ-523",
	},
	{
		email: "author21@gmail.com",
		phoneNumber: "89500335291",
		verifiedByEmail: true,
		role: "автор",
		firstName: "Алина",
		lastName: "Васильева",
		middleName: "Сергеевна",
		dateOfBirth: "16.03.1999",

		authorStatus: "Молодой ученый",
		region: "Респ. Башкортостан",
		city: "Уфа",
		university: "Уфимский Университет Науки и Технологий",
		faculty: "ИИГУ",
		department: "Химия",
		course: 4,
		groupNumber: "ХИМ-428",
	},
	{
		email: "author22@gmail.com",
		phoneNumber: "89500335292",
		verifiedByEmail: true,
		role: "автор",
		firstName: "Павел",
		lastName: "Романов",
		middleName: "Дмитриевич",
		dateOfBirth: "22.08.2000",

		authorStatus: "Специалитет",
		region: "Респ. Башкортостан",
		city: "Уфа",
		university: "Уфимский Университет Науки и Технологий",
		faculty: "ФАДЭТ",
		department: "Математика",
		course: 5,
		groupNumber: "МАТ-523",
	},
	{
		email: "author23@gmail.com",
		phoneNumber: "89500335293",
		verifiedByEmail: true,
		role: "автор",
		firstName: "Людмила",
		lastName: "Захарова",
		middleName: "Ивановна",
		dateOfBirth: "14.11.2001",

		authorStatus: "Бакалавриат",
		region: "Респ. Башкортостан",
		city: "Уфа",
		university: "Уфимский Университет Науки и Технологий",
		faculty: "ИТМ",
		department: "Информатика",
		course: 4,
		groupNumber: "ИНФ-428",
	},
	{
		email: "author24@gmail.com",
		phoneNumber: "89500335294",
		verifiedByEmail: true,
		role: "автор",
		firstName: "Наталья",
		lastName: "Кузьмина",
		middleName: "Владимировна",
		dateOfBirth: "01.06.1997",

		authorStatus: "Магистрант",
		region: "Респ. Башкортостан",
		city: "Уфа",
		university: "Уфимский Университет Науки и Технологий",
		faculty: "ПИШ",
		department: "Биология",
		course: 2,
		groupNumber: "БИО-224",
	},
	{
		email: "author25@gmail.com",
		phoneNumber: "89500335295",
		verifiedByEmail: true,
		role: "автор",
		firstName: "Сергей",
		lastName: "Попов",
		middleName: "Алексеевич",
		dateOfBirth: "25.05.1998",

		authorStatus: "Аспирант",
		region: "Респ. Башкортостан",
		city: "Уфа",
		university: "Уфимский Университет Науки и Технологий",
		faculty: "ИИГУ",
		department: "Химия",
		course: 3,
		groupNumber: "ХИМ-328",
	},
	{
		email: "author26@gmail.com",
		phoneNumber: "89500335296",
		verifiedByEmail: true,
		role: "автор",
		firstName: "Елена",
		lastName: "Сорокина",
		middleName: "Викторовна",
		dateOfBirth: "30.09.2002",

		authorStatus: "Бакалавриат",
		region: "Респ. Башкортостан",
		city: "Уфа",
		university: "Уфимский Университет Науки и Технологий",
		faculty: "ИГСН",
		department: "История",
		course: 3,
		groupNumber: "ИСТ-323",
	},
	{
		email: "author27@gmail.com",
		phoneNumber: "89500335297",
		verifiedByEmail: true,
		role: "автор",
		firstName: "Константин",
		lastName: "Громов",
		middleName: "Игоревич",
		dateOfBirth: "05.03.1996",

		authorStatus: "Магистрант",
		region: "Респ. Башкортостан",
		city: "Уфа",
		university: "Уфимский Университет Науки и Технологий",
		faculty: "ИИМРТ",
		department: "Физика",
		course: 2,
		groupNumber: "ФИЗ-224",
	},
	{
		email: "author28@gmail.com",
		phoneNumber: "89500335298",
		verifiedByEmail: true,
		role: "автор",
		firstName: "Игорь",
		lastName: "Лебедев",
		middleName: "Сергеевич",
		dateOfBirth: "27.11.1999",

		authorStatus: "Молодой ученый",
		region: "Респ. Башкортостан",
		city: "Уфа",
		university: "Уфимский Университет Науки и Технологий",
		faculty: "ИТМ",
		department: "Информатика",
		course: 4,
		groupNumber: "ИНФ-428",
	},
	{
		email: "author29@gmail.com",
		phoneNumber: "89500335299",
		verifiedByEmail: true,
		role: "автор",
		firstName: "Виктор",
		lastName: "Денисов",
		middleName: "Павлович",
		dateOfBirth: "12.12.1997",

		authorStatus: "Специалитет",
		region: "Респ. Башкортостан",
		city: "Уфа",
		university: "Уфимский Университет Науки и Технологий",
		faculty: "ФАДЭТ",
		department: "Математика",
		course: 5,
		groupNumber: "МАТ-523",
	},
	{
		email: "author30@gmail.com",
		phoneNumber: "89500335300",
		verifiedByEmail: true,
		role: "автор",
		firstName: "Ксения",
		lastName: "Фролова",
		middleName: "Алексеевна",
		dateOfBirth: "04.04.2000",

		authorStatus: "Бакалавриат",
		region: "Респ. Башкортостан",
		city: "Уфа",
		university: "Уфимский Университет Науки и Технологий",
		faculty: "ПИШ",
		department: "Биология",
		course: 4,
		groupNumber: "БИО-428",
	},
];

const moderators = [
	{
		email: "mod1@gmail.com",
		phoneNumber: "89500335261",
		verifiedByEmail: true,
		role: "модератор",
		firstName: "Мария",
		lastName: "Иванова",
		middleName: "Александровна",
		dateOfBirth: "12.03.1985",
		faculty: "ИГСН",
		department: "Физика",
		jobTitle: "Ассистент",
		verifiedByAdmin: true,
	},
	{
		email: "mod2@gmail.com",
		phoneNumber: "89500335262",
		verifiedByEmail: true,
		role: "модератор",
		firstName: "Андрей",
		lastName: "Смирнов",
		middleName: "Игоревич",
		dateOfBirth: "05.11.1980",
		faculty: "ИИМРТ",
		department: "Математика",
		jobTitle: "Старший преподаватель",
		verifiedByAdmin: true,
	},
	{
		email: "mod3@gmail.com",
		phoneNumber: "89500335263",
		verifiedByEmail: true,
		role: "модератор",
		firstName: "Елена",
		lastName: "Кузнецова",
		middleName: "Владимировна",
		dateOfBirth: "20.02.1988",
		faculty: "ФАДЭТ",
		department: "Информатика",
		jobTitle: "Доцент",
		verifiedByAdmin: true,
	},
	{
		email: "mod4@gmail.com",
		phoneNumber: "89500335264",
		verifiedByEmail: true,
		role: "модератор",
		firstName: "Сергей",
		lastName: "Петров",
		middleName: "Андреевич",
		dateOfBirth: "15.06.1975",
		faculty: "ИИГУ",
		department: "Химия",
		jobTitle: "Профессор",
		verifiedByAdmin: true,
	},
	{
		email: "mod5@gmail.com",
		phoneNumber: "89500335265",
		verifiedByEmail: true,
		role: "модератор",
		firstName: "Анна",
		lastName: "Волкова",
		middleName: "Николаевна",
		dateOfBirth: "08.09.1990",
		faculty: "ПИШ",
		department: "Биология",
		jobTitle: "Заведующий кафедрой",
		verifiedByAdmin: true,
	},
	{
		email: "mod6@gmail.com",
		phoneNumber: "89500335266",
		verifiedByEmail: true,
		role: "модератор",
		firstName: "Иван",
		lastName: "Морозов",
		middleName: "Алексеевич",
		dateOfBirth: "03.05.1982",
		faculty: "ИТМ",
		department: "Физика",
		jobTitle: "Ассистент",
		verifiedByAdmin: true,
	},
	{
		email: "mod7@gmail.com",
		phoneNumber: "89500335267",
		verifiedByEmail: true,
		role: "модератор",
		firstName: "Ольга",
		lastName: "Соколова",
		middleName: "Дмитриевна",
		dateOfBirth: "14.07.1984",
		faculty: "ИГСН",
		department: "Информатика",
		jobTitle: "Старший преподаватель",
		verifiedByAdmin: true,
	},
	{
		email: "mod8@gmail.com",
		phoneNumber: "89500335268",
		verifiedByEmail: true,
		role: "модератор",
		firstName: "Николай",
		lastName: "Новиков",
		middleName: "Павлович",
		dateOfBirth: "21.01.1977",
		faculty: "ИИМРТ",
		department: "Химия",
		jobTitle: "Профессор",
		verifiedByAdmin: true,
	},
	{
		email: "mod9@gmail.com",
		phoneNumber: "89500335269",
		verifiedByEmail: true,
		role: "модератор",
		firstName: "Светлана",
		lastName: "Михайлова",
		middleName: "Григорьевна",
		dateOfBirth: "10.10.1983",
		faculty: "ФАДЭТ",
		department: "Математика",
		jobTitle: "Доцент",
		verifiedByAdmin: true,
	},
	{
		email: "mod10@gmail.com",
		phoneNumber: "89500335270",
		verifiedByEmail: true,
		role: "модератор",
		firstName: "Алексей",
		lastName: "Лебедев",
		middleName: "Дмитриевич",
		dateOfBirth: "29.12.1992",
		faculty: "ПИШ",
		department: "Биология",
		jobTitle: "Заведующий кафедрой",
		verifiedByAdmin: true,
	},
];

module.exports = { moderators, authors };
